# Generated by Django 4.2.24 on 2025-09-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_finder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_value', models.EmailField(default='info@domainfinder.com', max_length=254)),
                ('email_description', models.CharField(default='We typically respond within 24 hours', max_length=200)),
                ('phone_value', models.CharField(default='+1 (555) 123-4567', max_length=50)),
                ('phone_description', models.CharField(default='Mon-Fri 9AM-6PM PST', max_length=200)),
                ('address_line1', models.CharField(default='123 Domain Street', max_length=200)),
                ('address_line2', models.CharField(default='San Francisco, CA 94105', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
                'ordering': ['-created_at'],
            },
        ),
    ]
