# Generated by Django 4.2.24 on 2025-09-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_finder', '0003_auto_20250920_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='admin_email',
            field=models.EmailField(default='admin@domainfinder.com', help_text='Email address where contact form messages will be sent', max_length=254),
        ),
    ]
