# Generated by Django 4.2.24 on 2025-09-20 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain_finder', '0004_contactinfo_admin_email'),
    ]

    operations = [
    ]
