# Generated by Django 4.2.24 on 2025-09-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_finder', '0005_auto_20250920_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='smtp_email',
            field=models.EmailField(blank=True, help_text='Gmail address for sending emails (e.g., your-email@gmail.com)', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='smtp_password',
            field=models.CharField(blank=True, help_text='Gmail App Password (16-character password from Google Account settings)', max_length=255, null=True),
        ),
    ]
