# Generated by Django 4.2.24 on 2025-09-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_finder', '0006_contactinfo_smtp_email_contactinfo_smtp_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='admin_email',
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='smtp_email',
            field=models.EmailField(blank=True, help_text='Gmail address for sending emails and receiving contact form messages', max_length=254, null=True),
        ),
    ]
