# Generated by Django 4.2.24 on 2025-09-20 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain_finder', '0007_remove_contactinfo_admin_email_and_more'),
    ]

    operations = [
    ]
