# Generated by Django 4.2.24 on 2025-09-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_finder', '0008_auto_20250920_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Domain name (e.g., TechStartup.com)', max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=10)),
                ('status', models.CharField(choices=[('premium', 'Premium'), ('featured', 'Featured'), ('new', 'New'), ('regular', 'Regular')], default='regular', help_text='Domain status/category', max_length=20)),
                ('description', models.TextField(help_text='Brief description of the domain and its potential use')),
                ('features', models.TextField(blank=True, help_text='Domain features/benefits (one per line)')),
                ('godaddy_url', models.URLField(blank=True, help_text='GoDaddy listing URL (optional)', max_length=500)),
                ('is_available', models.BooleanField(default=True, help_text='Is the domain currently available for sale?')),
                ('is_featured_on_homepage', models.BooleanField(default=False, help_text='Display this domain on the homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Domain for Sale',
                'verbose_name_plural': 'Domains for Sale',
                'ordering': ['-is_featured_on_homepage', '-created_at'],
            },
        ),
    ]
