# Generated by Django 4.2.24 on 2025-09-21 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain_finder', '0009_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Status name (e.g., Premium, Featured)', max_length=20, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly version (e.g., premium, featured)', max_length=20, unique=True)),
                ('badge_class', models.CharField(default='bg-gray-100 text-gray-800', help_text='CSS classes for the status badge (e.g., bg-green-100 text-green-800)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Is this status available for selection?')),
                ('sort_order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Domain Status',
                'verbose_name_plural': 'Domain Statuses',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='domain',
            name='status',
            field=models.ForeignKey(help_text='Domain status/category', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='domain_finder.domainstatus'),
        ),
    ]
