# Generated by Django 4.2.24 on 2025-09-21 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain_finder', '0010_domainstatus_alter_domain_status'),
    ]

    operations = [
    ]
