# Generated by Django 4.2.24 on 2025-09-21 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain_finder', '0011_auto_20250921_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Currency name (e.g., US Dollar, British Pound)', max_length=30, unique=True)),
                ('code', models.CharField(help_text='Currency code (e.g., USD, GBP, EUR)', max_length=3, unique=True)),
                ('symbol', models.CharField(help_text='Currency symbol (e.g., $, £, €)', max_length=5)),
                ('is_active', models.BooleanField(default=True, help_text='Is this currency available for selection?')),
                ('sort_order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='domain',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price value (e.g., 5000.00)', max_digits=10),
        ),
        migrations.AddField(
            model_name='domain',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Currency for the price', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='domain_finder.currency'),
        ),
    ]
