# Generated by Django 4.2.24 on 2025-09-21 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain_finder', '0012_currency_alter_domain_price_domain_currency'),
    ]

    operations = [
    ]
