# Generated by Django 4.2.24 on 2025-09-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_finder', '0013_auto_20250921_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='godaddy_url',
        ),
        migrations.AddField(
            model_name='domain',
            name='listing_url',
            field=models.URLField(blank=True, help_text='External listing URL (e.g., GoDaddy, Sedo, Flippa)', max_length=500),
        ),
        migrations.AddField(
            model_name='domain',
            name='website_name',
            field=models.CharField(blank=True, default='GoDaddy', help_text='Name of the marketplace/website (e.g., GoDaddy, Sedo, Flippa)', max_length=50),
        ),
    ]
