# Generated by Django 4.2.24 on 2025-09-21 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain_finder', '0014_remove_domain_godaddy_url_domain_listing_url_and_more'),
    ]

    operations = [
    ]
