# Generated by Django 4.2.24 on 2025-09-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_finder', '0015_auto_20250921_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='direct_to_contact',
            field=models.BooleanField(default=False, help_text='If checked, the button will direct to contact page instead of external listing'),
        ),
    ]
