# Generated by Django 4.2.24 on 2025-09-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_finder', '0016_domain_direct_to_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author_avatar',
            field=models.URLField(blank=True, help_text='Author profile image URL. If empty, a default avatar will be used.', max_length=500),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_bio',
            field=models.TextField(blank=True, help_text='Author biography. If empty, a default bio will be used.', max_length=500),
        ),
    ]
