# Generated by Django 4.2.24 on 2025-09-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_finder', '0017_blogpost_author_avatar_blogpost_author_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Author's full name", max_length=100)),
                ('bio', models.TextField(blank=True, help_text='Author biography. If empty, a default bio will be used.', max_length=500)),
                ('avatar', models.URLField(blank=True, help_text='Author profile image URL. If empty, a default avatar will be used.', max_length=500)),
                ('email', models.EmailField(blank=True, help_text="Author's email address (optional)", max_length=254)),
                ('website', models.URLField(blank=True, help_text="Author's personal website (optional)")),
                ('is_active', models.BooleanField(default=True, help_text='Whether this author is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='author_avatar',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='author_bio',
        ),
    ]
