# Generated by Django 4.2.24 on 2025-09-22 21:26

from django.db import migrations


def populate_authors(apps, schema_editor):
    """Create Author records from existing BlogPost author names."""
    BlogPost = apps.get_model('domain_finder', 'BlogPost')
    Author = apps.get_model('domain_finder', 'Author')
    
    # Get unique author names from existing blog posts
    unique_authors = set()
    for post in BlogPost.objects.all():
        if post.author.strip():  # Only add non-empty author names
            unique_authors.add(post.author.strip())
    
    # Create Author records for unique names
    for author_name in unique_authors:
        Author.objects.get_or_create(
            name=author_name,
            defaults={
                'bio': '',  # Empty bio will use default from display_bio property
                'avatar': '',  # Empty avatar will use default fallback
                'is_active': True,
            }
        )


def reverse_populate_authors(apps, schema_editor):
    """Remove all authors (reverse operation)."""
    Author = apps.get_model('domain_finder', 'Author')
    Author.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('domain_finder', '0018_create_author_model'),
    ]

    operations = [
        migrations.RunPython(populate_authors, reverse_populate_authors),
    ]
