# Generated by Django 4.2.24 on 2025-09-22 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain_finder', '0019_populate_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author_new',
            field=models.ForeignKey(blank=True, help_text='Select the author for this blog post', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='domain_finder.author'),
        ),
    ]
