# Generated by Django 4.2.24 on 2025-09-22 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain_finder', '0021_link_posts_to_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author_new',
            field=models.ForeignKey(default=1, help_text='Select the author for this blog post', on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='domain_finder.author'),
            preserve_default=False,
        ),
    ]
