# Generated by Django 4.2.24 on 2025-09-22 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain_finder', '0022_remove_old_author_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='author_new',
            new_name='author',
        ),
    ]
