# Generated by Django 4.2.24 on 2025-09-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_finder', '0023_remove_old_author_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Main headline. You can use HTML like <span class='text-primary'>Domain</span>", max_length=200)),
                ('subtitle', models.TextField(help_text='Description text below the main headline', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Set to True to use this content on homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Content',
                'verbose_name_plural': 'Homepage Content',
                'ordering': ['-updated_at'],
            },
        ),
    ]
