# Generated by Django 4.2.24 on 2025-09-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_finder', '0024_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Hero image for the homepage. Leave empty to use default image.', null=True, upload_to='homepage/hero/'),
        ),
    ]
