# Generated by Django 4.2.24 on 2025-09-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_finder', '0025_homepage_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='from_email',
            field=models.CharField(default='Domain Finder <noreply@domainfinder.uk>', help_text="The 'From' address that appears in outgoing emails. Format: 'Your Business Name <email@domain.com>'", max_length=255),
        ),
    ]
