# Generated by Django 4.2.24 on 2025-10-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_finder', '0026_contactinfo_from_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='client_satisfaction',
            field=models.CharField(default='98%', help_text="Client satisfaction percentage (e.g., '98%', '99%')", max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='client_satisfaction_label',
            field=models.CharField(default='Client Satisfaction', help_text='Label for client satisfaction statistic', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='domains_analyzed',
            field=models.CharField(default='500+', help_text="Number of domains analyzed (e.g., '500+', '1000+')", max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='domains_analyzed_label',
            field=models.CharField(default='Domains Analyzed', help_text='Label for domains analyzed statistic', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='response_time',
            field=models.CharField(default='24h', help_text="Average response time (e.g., '24h', '12h')", max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='response_time_label',
            field=models.CharField(default='Avg. Response Time', help_text='Label for response time statistic', max_length=50),
        ),
    ]
