# Generated by Django 4.2.24 on 2025-10-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_finder', '0027_homepage_client_satisfaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='card1_label',
            field=models.CharField(default='Accuracy Rate', help_text='Label for first analytics card number', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='card1_number',
            field=models.CharField(default='94%', help_text='Number/percentage for first analytics card', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='card1_subtitle',
            field=models.CharField(default='Real-time analysis of domain market trends and pricing patterns', help_text='Subtitle for first analytics card', max_length=150),
        ),
        migrations.AddField(
            model_name='homepage',
            name='card1_title',
            field=models.CharField(default='Market Trends', help_text='Title for first analytics card', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='card2_label',
            field=models.CharField(default='Match Score', help_text='Label for second analytics card number', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='card2_number',
            field=models.CharField(default='89%', help_text='Number/percentage for second analytics card', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='card2_subtitle',
            field=models.CharField(default='Evaluate how well domains match your brand identity and goals', help_text='Subtitle for second analytics card', max_length=150),
        ),
        migrations.AddField(
            model_name='homepage',
            name='card2_title',
            field=models.CharField(default='Brand Alignment', help_text='Title for second analytics card', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='card3_label',
            field=models.CharField(default='Clean Domains', help_text='Label for third analytics card number', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='card3_number',
            field=models.CharField(default='99%', help_text='Number/percentage for third analytics card', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='card3_subtitle',
            field=models.CharField(default='Comprehensive domain history and legal risk evaluation', help_text='Subtitle for third analytics card', max_length=150),
        ),
        migrations.AddField(
            model_name='homepage',
            name='card3_title',
            field=models.CharField(default='Risk Assessment', help_text='Title for third analytics card', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='market_intelligence_pill',
            field=models.CharField(default='Market Intelligence', help_text='Text for the pill button (without emoji)', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='market_intelligence_subtitle',
            field=models.TextField(default='Our comprehensive analytics provide deep insights into domain performance, market trends, and competitive landscape.', help_text='Subtitle description for Market Intelligence section', max_length=300),
        ),
        migrations.AddField(
            model_name='homepage',
            name='market_intelligence_title',
            field=models.CharField(default='Data-Driven Domain Research', help_text='Main title for Market Intelligence section', max_length=100),
        ),
    ]
