# Generated by Django 4.2.24 on 2025-10-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_finder', '0028_homepage_card1_label_homepage_card1_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='show_advanced_analytics',
            field=models.BooleanField(default=False, help_text='Show/Hide the Advanced Analytics section on homepage'),
        ),
    ]
