# Generated by Django 4.2.24 on 2025-10-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_finder', '0029_homepage_show_advanced_analytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Service name (e.g., 'Domain Market Research & Analysis')", max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide this service on the contact page')),
                ('sort_order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Service',
                'verbose_name_plural': 'Contact Services',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Page Content', 'verbose_name_plural': 'Contact Page Content'},
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='services_subtitle',
            field=models.CharField(default='What we can help you with', help_text='Subtitle for the services section', max_length=200),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='services_title',
            field=models.CharField(default='Our Services', help_text='Title for the services section', max_length=100),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='show_services',
            field=models.BooleanField(default=True, help_text='Show/hide the Our Services section on contact page'),
        ),
    ]
