# Generated by Django 4.2.24 on 2025-10-18 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain_finder', '0030_contact_services_dynamic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Home Page Content', 'verbose_name_plural': 'Home Page Content'},
        ),
        migrations.AddField(
            model_name='contactservice',
            name='contact_info',
            field=models.ForeignKey(blank=True, help_text='Associated contact page content', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='domain_finder.contactinfo'),
        ),
    ]
