# Generated by Django 4.2.24 on 2025-10-18 16:03

from django.db import migrations


def link_services_to_contact_info(apps, schema_editor):
    """Link existing ContactService records to the active ContactInfo."""
    ContactInfo = apps.get_model('domain_finder', 'ContactInfo')
    ContactService = apps.get_model('domain_finder', 'ContactService')
    
    # Get or create active contact info
    active_contact_info = ContactInfo.objects.filter(is_active=True).first()
    if not active_contact_info:
        active_contact_info = ContactInfo.objects.create(
            email_value="info@domainfinder.com",
            is_active=True
        )
    
    # Link all existing services to the active contact info
    ContactService.objects.filter(contact_info__isnull=True).update(
        contact_info=active_contact_info
    )


def reverse_link_services(apps, schema_editor):
    """Reverse migration - set all contact_info to null."""
    ContactService = apps.get_model('domain_finder', 'ContactService')
    ContactService.objects.update(contact_info=None)


class Migration(migrations.Migration):

    dependencies = [
        ('domain_finder', '0031_add_contactservice_foreignkey'),
    ]

    operations = [
        migrations.RunPython(link_services_to_contact_info, reverse_link_services),
    ]
