# Generated by Django 4.2.24 on 2025-10-18 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain_finder', '0032_link_services_to_contact_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactservice',
            name='contact_info',
            field=models.ForeignKey(default=1, help_text='Associated contact page content', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='domain_finder.contactinfo'),
            preserve_default=False,
        ),
    ]
