# Generated by Django 4.2.24 on 2025-10-18 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain_finder', '0033_make_contactservice_foreignkey_required'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactservice',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
    ]
