# Generated by Django 4.2.24 on 2025-10-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_finder', '0034_contact_expectations_dynamic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text="CSS class for icon (e.g., 'fas fa-clock')", max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Expectation Item',
                'verbose_name_plural': 'Expectation Items',
                'ordering': ['order', 'title'],
            },
        ),
    ]
