# Generated by Django 4.2.24 on 2025-10-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_finder', '0035_expectationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='show_what_to_expect',
            field=models.BooleanField(default=True, help_text='Show/hide the What to Expect section on contact page'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='what_to_expect_title',
            field=models.CharField(default='What to Expect', help_text='Title for the What to Expect section', max_length=100),
        ),
    ]
